### ISSUE TITLE
Browser compatible build

### ISSUE THREAD

**Issue by mulhoon** [JasonStorey/teoria-chord-progression#2]
Hi, this script looks very useful.
I'm just wondering how I can use the browser compatible build without require. i.e. how can I make teoriaChordProgression available for use?

Thanks

**Comment by mulhoon** [comment]
Ah, I found it globally as `progression`. Might be worth mentioning in the docs for others.

Thanks

**Comment by JasonStorey** [comment]
Ack... you're not wrong. I'll add something to the docs. Thanks!

**Comment by JasonStorey** [comment]
I've updated the browser global to `teoriaChordProgression` - thought it was a more sensible name - and added a note to the docs.

Let me know if you spot anything else. Happy to implement new features or take pull requests.

Thanks again.

**Comment by mulhoon** [comment]
Thanks!
